services:
  aria2-with-aria2ng:
    build: .
    container_name: aria2-with-aria2ng
    restart: always
    ports:
      - "8080:80"
      - "6800:6800"
      - "19101:19101"
      - "19101:19101/udp"
    environment:
      - RPC_SECRET=${RPC_SECRET:-}   # 不设置则不启用 RPC 密钥
    volumes:
      - /Downloads:/downloads

